workflows:
  ios_appstore_manual_signing:
    name: iOS App Store Manual signing
    max_build_duration: 60

    environment:
      groups:
        - signing
        - appstore_connect
      vars:
        XCODE_PROJECT: "Finance-Regret-Manager.xcodeproj"
        XCODE_SCHEME: "Finance-Regret-Manager"
        BUNDLE_ID: "com.financeregret.denys1er"
        TEAM_ID: "OVERRIDE_BY_PROFILE"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: Import certificate and provisioning profile
        script: |
          set -euo pipefail

          # --- Secrets (support alternate names) ---
          CERT_P12_B64="${CERTIFICATE_P12:-${CERT_P12:-}}"
          CERT_PWD="${CERTIFICATE_PASSWORD:-${CERT_PASSWORD:-}}"
          PROFILE_B64="${MOBILEPROVISION:-${PROFILE_MOBILEPROVISION:-}}"

          [ -n "$CERT_P12_B64" ] || { echo "❌ Missing CERTIFICATE_P12 (or CERT_P12)"; exit 1; }
          [ -n "$PROFILE_B64" ]  || { echo "❌ Missing MOBILEPROVISION (or PROFILE_MOBILEPROVISION)"; exit 1; }
          [ -n "${CERT_PWD:-}" ] || { echo "❌ Missing CERTIFICATE_PASSWORD (or CERT_PASSWORD)"; exit 1; }

          # --- Robust base64 decode for macOS runners ---
          b64dec() { (base64 --decode 2>/dev/null || base64 -D); }

          printf "%s" "$CERT_P12_B64" | tr -d '\r' | b64dec > cert.p12
          printf "%s" "$PROFILE_B64"  | tr -d '\r' | b64dec > profile.mobileprovision

          # --- Diagnostics BEFORE import (safe) ---
          echo "== cert.p12 diagnostics =="
          ls -lah cert.p12
          file cert.p12 || true
          echo "bytes: $(wc -c < cert.p12 || true)"

          echo "== Validate pkcs12 readability =="
          openssl pkcs12 -info -in cert.p12 -noout -passin pass:"$CERT_PWD"

          # --- Keychain + certificate ---
          keychain initialize
          keychain add-certificates --certificate cert.p12 --certificate-password "$CERT_PWD"

          # --- Install profile and extract UUID + TeamIdentifier ---
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_PLIST="$(security cms -D -i profile.mobileprovision)"
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< "$PROFILE_PLIST")
          PROFILE_TEAM_ID=$(/usr/libexec/PlistBuddy -c 'Print TeamIdentifier:0' /dev/stdin <<< "$PROFILE_PLIST")

          cp profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"
          echo "Using Provisioning Profile UUID: $PROFILE_UUID"
          echo "TeamIdentifier from profile: $PROFILE_TEAM_ID"

          # export to env for next steps
          echo "PROFILE_UUID=$PROFILE_UUID" >> "$CM_ENV"
          echo "TEAM_ID=$PROFILE_TEAM_ID"   >> "$CM_ENV"

          # Resolve signing identity
          DIST_IDENTITY="$(security find-identity -v -p codesigning | sed -nE 's/.*"((Apple|iPhone) Distribution:.*)"/\1/p' | head -n1 || true)"
          if [ -z "$DIST_IDENTITY" ]; then
            echo "❌ Distribution identity not found in keychain"
            security find-identity -v -p codesigning || true
            exit 1
          fi
          echo "DIST_IDENTITY=$DIST_IDENTITY" >> "$CM_ENV"
          echo "Using signing identity: $DIST_IDENTITY"

          echo "== Code signing identities in keychain =="
          security find-identity -v -p codesigning || true

          # --- exportOptions.plist (manual) ---
          cat > exportOptions.plist <<EOI
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key><string>${PROFILE_UUID}</string>
            </dict>
            <key>stripSwiftSymbols</key><true/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOI
          /usr/bin/plutil -lint exportOptions.plist

          # Apply profile into the project (manual signing)
          xcode-project use-profiles --project "$XCODE_PROJECT" --export-options-plist exportOptions.plist

      - name: Prepare versions (no Info.plist)
        script: |
          set -euo pipefail

          BUILD_NUM="${APP_BUILD:-$(date +%y%j%H%M%S)}"
          echo "BUILD_NUM=$BUILD_NUM" >> "$CM_ENV"

          if [ -n "${APP_VERSION:-}" ]; then
            echo "APP_VERSION=$APP_VERSION" >> "$CM_ENV"
          fi

          echo "== Planned versions =="
          echo "MARKETING_VERSION=${APP_VERSION:-(unchanged)}"
          echo "CURRENT_PROJECT_VERSION=$BUILD_NUM"

      - name: Archive and export IPA (xcodebuild)
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/Finance-Regret-Manager.xcarchive"
          EXPORT_PATH="$CM_EXPORT_DIR"

          EXTRA_FLAGS=( CURRENT_PROJECT_VERSION="$BUILD_NUM" )
          if [ -n "${APP_VERSION:-}" ]; then
            EXTRA_FLAGS+=( MARKETING_VERSION="$APP_VERSION" )
          fi

          echo "Archiving to: $ARCHIVE_PATH"
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            "${EXTRA_FLAGS[@]}"

          echo "Exporting IPA to: $EXPORT_PATH"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_PATH"

          echo "Export dir listing:"
          ls -lah "$EXPORT_PATH" || true
          test -e "$EXPORT_PATH"/*.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_EXPORT_DIR/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
